# Generated by Django 2.1.2 on 2019-03-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190329_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
