# Generated by Django 2.1.2 on 2019-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='tea_type',
            field=models.IntegerField(choices=[(1, 'BP1'), (2, 'PF1'), (3, 'PDUST'), (4, 'DUST1')], default=1),
        ),
    ]
