# Generated by Django 2.1.2 on 2019-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190409_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='tea_type',
            field=models.IntegerField(blank=True, choices=[(1, 'BP1'), (2, 'PF1'), (3, 'PDUST'), (4, 'DUST1')], default=1, null=True),
        ),
    ]
