# Generated by Django 2.1.2 on 2019-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0004_auto_20190409_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(null=True, upload_to='gallery'),
        ),
    ]
